CREATE TABLE employees.employee (
    id         bigint                    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    birth_date date                      NOT NULL,
    first_name varchar(14)               NOT NULL,
    last_name  varchar(16)               NOT NULL,
    gender     employees.employee_gender NOT NULL,
    hire_date  date                      NOT NULL
);
